name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    name: Building and pushing ${{ matrix.app }}
    strategy:
      matrix:
        app: [hello-backend, hello-frontend]
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t oglagovskiy/${{ matrix.app }}:latest -f ./docker/${{ matrix.app }}/Dockerfile ./src/${{ matrix.app }}
